import type { Task } from './types';

export const mockTasks: Task[] = [
  // ── TODO (Not Started) ──────────────────────────────────────────
  {
    id: 't1',
    title: 'Implement New Feature',
    description: "Add a 'dark mode' option for improved UX across all pages.",
    priority: 'medium',
    dueDate: '2026-07-15T00:00:00.000Z',
    assignee: 'Devrizal Pratama',
    status: 'todo',
    tags: ['frontend', 'ux'],
    createdAt: '2026-06-01T08:30:00.000Z',
  },
  {
    id: 't2',
    title: 'Fix Bug - On Payment',
    description: "The 'save' button is not working on mobile payment page.",
    priority: 'high',
    dueDate: '2026-06-10T00:00:00.000Z', // OVERDUE
    assignee: 'Hanna Philips',
    status: 'todo',
    tags: ['bug', 'backend'],
    createdAt: '2026-05-20T09:00:00.000Z',
  },
  {
    id: 't3',
    title: 'Review Design - Final',
    description: 'Provide feedback on the latest UI prototypes from design team.',
    priority: 'medium',
    dueDate: '2026-07-17T00:00:00.000Z',
    assignee: 'Talan Korsgaard',
    status: 'todo',
    tags: ['review', 'ux'],
    createdAt: '2026-06-05T10:15:00.000Z',
  },
  {
    id: 't4',
    title: 'New Version - Quality Check',
    description: 'Conduct thorough testing of updated software release candidate.',
    priority: 'low',
    dueDate: '2026-06-20T00:00:00.000Z', // OVERDUE
    assignee: 'Davis Donin',
    status: 'todo',
    tags: ['testing'],
    createdAt: '2026-05-27T07:45:00.000Z',
  },

  // ── IN PROGRESS ─────────────────────────────────────────────────
  {
    id: 't5',
    title: 'Fix Bug - Mobile Compatibility',
    description: 'The app is crashing on some Android devices running OS 13+.',
    priority: 'high',
    dueDate: '2026-06-15T00:00:00.000Z', // OVERDUE
    assignee: 'Devrizal Pratama',
    status: 'in-progress',
    tags: ['bug', 'frontend'],
    createdAt: '2026-04-17T11:00:00.000Z',
  },
  {
    id: 't6',
    title: 'Review Marketing Campaign',
    description: 'Analyze the effectiveness of recent social media ad campaigns.',
    priority: 'medium',
    dueDate: '2026-07-18T00:00:00.000Z',
    assignee: 'Hanna Philips',
    status: 'in-progress',
    tags: ['review'],
    createdAt: '2026-05-10T14:30:00.000Z',
  },
  {
    id: 't7',
    title: 'Conduct User Research',
    description: 'Gather feedback from users to identify pain points and areas for improvement.',
    priority: 'medium',
    dueDate: '2026-07-17T00:00:00.000Z',
    assignee: 'Talan Korsgaard',
    status: 'in-progress',
    tags: ['testing', 'ux'],
    createdAt: '2026-06-06T09:30:00.000Z',
  },
  {
    id: 't8',
    title: 'Update Documentation',
    description: 'Ensure all documentation is updated and accurate for v2.0 release.',
    priority: 'high',
    dueDate: '2026-06-25T00:00:00.000Z', // OVERDUE
    assignee: 'Davis Donin',
    status: 'in-progress',
    tags: ['review', 'backend'],
    createdAt: '2026-05-27T08:00:00.000Z',
  },

  // ── DONE ────────────────────────────────────────────────────────
  {
    id: 't9',
    title: 'Optimize Database Performance',
    description: 'Improve database query efficiency & scalability for production.',
    priority: 'low',
    dueDate: '2026-05-15T00:00:00.000Z',
    assignee: 'Devrizal Pratama',
    status: 'done',
    tags: ['backend', 'feature'],
    createdAt: '2026-04-17T10:00:00.000Z',
  },
  {
    id: 't10',
    title: 'Improve API Security',
    description: 'Enhance API security measures to protect against common vulnerabilities.',
    priority: 'high',
    dueDate: '2026-06-18T00:00:00.000Z',
    assignee: 'Hanna Philips',
    status: 'done',
    tags: ['auth', 'backend'],
    createdAt: '2026-05-10T13:00:00.000Z',
  },
  {
    id: 't11',
    title: 'Implement API for Task Creation',
    description: 'Develop an API endpoint to create new tasks with full validation.',
    priority: 'medium',
    dueDate: '2026-06-11T00:00:00.000Z',
    assignee: 'Talan Korsgaard',
    status: 'done',
    tags: ['feature', 'backend'],
    createdAt: '2026-05-27T12:00:00.000Z',
  },
  {
    id: 't12',
    title: 'Setup CI/CD Pipeline',
    description: 'Configure automated build, test, and deployment pipeline for staging.',
    priority: 'low',
    dueDate: '2026-05-30T00:00:00.000Z',
    assignee: 'Davis Donin',
    status: 'done',
    tags: ['backend'],
    createdAt: '2026-05-01T08:00:00.000Z',
  },
];
